server:
  port: 8080
  max_size: 8 # Calculate by megabyte
  valid_token: "VALID_TOKEN"
database:
  uri: "root:123456@/moges?charset=utf8&parseTime=True&loc=Local"
  maxIdle: 5
  maxOpen: 10
  showSql: true
